version: '3'

services:
  ty-customer:
    image: cloud-nacos
    container_name: cloud-nacos
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/cloud-nacos/logs/:/cloud-nacos/logs
    privileged: true
    network_mode: "host"